version: '3.8'

services:
  backend:
    build: ./backsight-server
    ports:
      - "3001:3001"
    volumes:
      - ./backsight-server/database.db:/app/database.db 
    restart: always

  frontend:
    build: ./backsight-client
    ports:
      - "80:80" 
    depends_on:
      - backend
    restart: always